export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const ADD_TODOLIST = 'ADD_TODOLIST'
export const GET_TODOLIST = 'GET_TODOLIST'
export const TODOLIST_ERROR = 'TODOLIST_ERROR'
export const DELETE_TODOLIST = 'DELETE_TODOLIST'
export const ADD_TODO = 'ADD_TODO'
export const GET_TODOS = 'GET_TODOS'
export const DELETE_TODO = 'DELETE_TODO'
export const COMPLETE_TODO = 'COMPLETE_TODO'

